format_version: v1.0
type: GeneratorComponent
attributes: {id: netPres}
children:
- type: Symbols
  children:
  - type: Menu
    attributes: {id: NET_PRES_RTOS_MENU}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: NET_PRES_SYS_RTOS_TASK}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
- type: Instances
  children:
  - type: InstanceComponent
    attributes: {instance: '0', id: netPres}
    children:
    - type: Symbols
      children:
      - type: Boolean
        attributes: {id: NET_PRES_SUPPORT_DATAGRAM_IDX0}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: netPres_0, value: 'true'}
      - type: Boolean
        attributes: {id: NET_PRES_SUPPORT_STREAM_IDX0}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: netPres_0, value: 'true'}
- type: ElementPosition
  attributes: {x: '573', y: '221', id: netPres}
